[project]
name = "beerwulf-assessment"
version = "0.1.0"
description = "A simple ETL project for Beerwulf data assessment."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "sqlalchemy>=2.0.38",
]

[dependency-groups]
dev = [
    "ruff>=0.9.6",
]
