name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruff
        uses: astral-sh/ruff-action@v3
        with:
          src: "./etl"
      - name: Check via Ruff
        run: ruff check
      - name: Format via Ruff
        run: ruff format
